/**************************************************************************************************
Name:       spPortal_MaintainDeletedData
Purpose:    Stored procedure to maintain DELETED portal data

Date        User            Change
---------------------------------------------------------------------------------------------
08/24/2022	DK				Original procedure
01/24/2023	DK				Add a list of protected tables (skip these tables)
---------------------------------------------------------------------------------------------

EXEC spPortal_MaintainDeletedData 60
***************************************************************************************************/
CREATE OR ALTER PROCEDURE dbo.spPortal_MaintainDeletedData
      (@days		INT	= 1000)
AS
BEGIN
SET NOCOUNT ON

DECLARE @log_id			INT
	   ,@cutoff_date	DATE
	   ,@table_name		VARCHAR(200)
	   
--*************************************************************************************************
-- Calculate the cutoff date
--*************************************************************************************************
SELECT @cutoff_date = CONVERT(VARCHAR(20), DATEADD(day, -@days, GETDATE()), 101)

--*************************************************************************************************
-- Create a table of table names to loop through
--*************************************************************************************************
IF OBJECT_ID('tempdb.dbo.#table_names') IS NOT NULL
	BEGIN DROP TABLE #table_names END

CREATE TABLE #table_names
      (table_name	VARCHAR(200))

-- Only insert tables that are in the dbo schema and have a DELETED column
INSERT INTO #table_names
      (table_name)
SELECT T.name
  FROM QA06_PORTAL.sys.tables	T
  JOIN QA06_PORTAL.sys.schemas	S
    ON T.schema_id				= S.schema_id
  JOIN QA06_PORTAL.sys.columns	C
    ON T.object_id				= C.object_id
 WHERE S.name					= 'dbo'
   AND C.name					= 'DELETED'

--*************************************************************************************************
-- Create a list of protected tables
--*************************************************************************************************
IF OBJECT_ID('tempdb.dbo.#protected_table_names') IS NOT NULL
	BEGIN DROP TABLE #protected_table_names END

CREATE TABLE #protected_table_names
      (table_name	VARCHAR(200))

INSERT INTO #protected_table_names(table_name) VALUES ('API_ERROR')
INSERT INTO #protected_table_names(table_name) VALUES ('API_SECURITY_EXCEPTION')
INSERT INTO #protected_table_names(table_name) VALUES ('APP_LINK')
INSERT INTO #protected_table_names(table_name) VALUES ('APPLICATION_MODULE_PAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('APPLICATION_PROPERTIES')
INSERT INTO #protected_table_names(table_name) VALUES ('BUSINESS_RULE')
INSERT INTO #protected_table_names(table_name) VALUES ('CSS')
INSERT INTO #protected_table_names(table_name) VALUES ('CSS_PROPERTY')
INSERT INTO #protected_table_names(table_name) VALUES ('CSS_PROPERTY_LOOKUP')
INSERT INTO #protected_table_names(table_name) VALUES ('ELEMENT')
INSERT INTO #protected_table_names(table_name) VALUES ('ELEMENT_GROUP')
INSERT INTO #protected_table_names(table_name) VALUES ('ELEMENT_GROUP_ELEMENT')
INSERT INTO #protected_table_names(table_name) VALUES ('ELEMENT_PROPERTY')
INSERT INTO #protected_table_names(table_name) VALUES ('ELEMENT_VALUE_LIST')
INSERT INTO #protected_table_names(table_name) VALUES ('ENROLL_RULE')
INSERT INTO #protected_table_names(table_name) VALUES ('ENROLL_TYPE_RULE')
INSERT INTO #protected_table_names(table_name) VALUES ('ENROLLMENT_TYPE_WORKFLOW')
INSERT INTO #protected_table_names(table_name) VALUES ('FEATURE_ENTITY')
INSERT INTO #protected_table_names(table_name) VALUES ('FEATURE_PAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('FEATURE_ROLE')
INSERT INTO #protected_table_names(table_name) VALUES ('FILE_ACCESS')
INSERT INTO #protected_table_names(table_name) VALUES ('FILE_ATTACHMENT')
INSERT INTO #protected_table_names(table_name) VALUES ('FILE_CONTENT_ASSOCIATION')
INSERT INTO #protected_table_names(table_name) VALUES ('FILE_DETAIL')
INSERT INTO #protected_table_names(table_name) VALUES ('FILE_DETAIL_ASSOCIATION')
INSERT INTO #protected_table_names(table_name) VALUES ('FILE_REPOSITORY')
INSERT INTO #protected_table_names(table_name) VALUES ('file_repository_20230119')
INSERT INTO #protected_table_names(table_name) VALUES ('FILE_SUBSYSTEM')
INSERT INTO #protected_table_names(table_name) VALUES ('file_subsystem_20230119')
INSERT INTO #protected_table_names(table_name) VALUES ('FILE_TEMPLATE')
INSERT INTO #protected_table_names(table_name) VALUES ('FOLDER_MENU')
INSERT INTO #protected_table_names(table_name) VALUES ('FOLDER_MENU_CONFIG')
INSERT INTO #protected_table_names(table_name) VALUES ('FORM')
INSERT INTO #protected_table_names(table_name) VALUES ('FORM_MAIL')
INSERT INTO #protected_table_names(table_name) VALUES ('FORM_NON_RBA')
INSERT INTO #protected_table_names(table_name) VALUES ('FORM_NON_RBA_CERT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('FORM_REQUEST')
INSERT INTO #protected_table_names(table_name) VALUES ('FORM_SECTION')
INSERT INTO #protected_table_names(table_name) VALUES ('FORM_SECTION_ELEMENT')
INSERT INTO #protected_table_names(table_name) VALUES ('FORM_SECTION_ELEMENT_GRP')
INSERT INTO #protected_table_names(table_name) VALUES ('FORM_SECTION_ELEMENT_PROP')
INSERT INTO #protected_table_names(table_name) VALUES ('HOME_PAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_ACTION')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_BACKUP_LIST')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_CSS')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_CSS_PROPERTY')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_CSS_PROPERTY_LOOKUP')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_DIV')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_DIV_ACTIONS')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_DIV_ELEMENTS')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_ELEMENT')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_ELEMENT_LOOKUP_FILTERS')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_ELEMENT_PROPERTY')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_ELEMENT_PROPERTY_LIMIT')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_ELEMENT_PROPERTY_LOOKUP')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_FEATURE_MENU_LINK')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_FOLDER_MENU')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_IMAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_LANGUAGE_EDITOR_FILES')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_LOCALIZED_LABEL')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_MENU_LINK')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_PAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_PAGE_DIV')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_QUERY')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_USER_MENU_CONFIG')
INSERT INTO #protected_table_names(table_name) VALUES ('HTML_USER_MESSAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('INQUIRY_RECIPIENT')
INSERT INTO #protected_table_names(table_name) VALUES ('INQUIRY_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ACCESS_RIGHTS_SOURCE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ACCOUNT_NUMBER_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ACCOUNT_TRAN_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ACCREDITATION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ACKNOWLEDGMENT_REQUESTED')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ACTION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ADDRESS_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ADJUSTMENT_REASON_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ADMISSION_SOURCE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ADMISSION_SOURCE_NB_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ADMISSION_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_AFFILIATION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ALLERGY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ALLERGY_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_AMBULANCE_TRANS_RSN_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_AMBULANCE_TRANSPORT_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_AMOUNT_QUALIFIER_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_AMOUNT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_APPLICATION_MODULE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_APPLICATION_PAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ATTRIBUTE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_AUTH_RULE_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_AUTH_RULE_USAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_AUTH_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_AUTH_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_AUTHENTICATION_SCHEME')
INSERT INTO #protected_table_names(table_name) VALUES ('L_BENEFIT_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_BENEFIT_LIMIT_LEVEL')
INSERT INTO #protected_table_names(table_name) VALUES ('L_BENEFIT_LIMIT_NETWORK')
INSERT INTO #protected_table_names(table_name) VALUES ('L_BENEFIT_LIMIT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_BENEFIT_PLAN_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_BENEFIT_STATUS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_BENEFIT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_BRAND_GENERIC')
INSERT INTO #protected_table_names(table_name) VALUES ('L_BROKEN_APPOINTMENT_REASON')
INSERT INTO #protected_table_names(table_name) VALUES ('L_BROKER_REG_ENTRY_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CARE_MANAGEMENT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CATEGORY_ITEM')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CERTIFICATION_ACTION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CERTIFICATION_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CERTIFICATION_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CITIZENSHIP_STATUS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_ADJ_GROUP_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_ADJ_RSN_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_DIAGNOSIS_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_FILING_IND_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_FREQUENCY_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_PAYMENT_STATUS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_RELATIONSHIP_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_REQUEST_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_STATUS_CAT_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_STATUS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CLAIM_VALUE_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_COB_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_COB_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_COBRA_QUALIFYING_EVT_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CODE_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CODE_LIST_QUALIFIER_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CODE_SET')
INSERT INTO #protected_table_names(table_name) VALUES ('L_COMM_NUMBER_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_COMMENT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_COMMISSION_IND_GROUP_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_COMMISSION_REMARK_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CONDITION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CONDITION_CODE_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CONDITION_GROUP')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CONDITION_INDICATOR')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CONFIG_USAGE_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CONTACT_FUNCTION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CONTENT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CONTRACT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_COPAY_STATUS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_COUNTRY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_COUNTRY_SUBDIVISION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_COVERAGE_LEVEL_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CREDIT_DEBIT_FLAG_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CURR_HEALTH_COND_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_CURRENCY_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DATA_SYNTAX_ERROR')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DATA_VISIBILITY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DATE_FORMAT_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DATE_TIME_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DEA_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DELAY_REASON_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DELIVERY_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DFI_ID_NUMBER_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DIAGNOSIS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DISABILITY_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DISCIPLINE_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DISEASE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DRG_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DRUG_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DRUG_DOSAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DRUG_ID_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DRUG_INTERACTION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DRUG_ROUTE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_DRUG_SUB_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_EFT_REASON_FOR_SUBMISSION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_EHB_VAR_REASON')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ELEMENT_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ELIG_OR_BENEFIT_INFO')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ELIGIBILITY_CHANGE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ELIGIBILITY_RESTRICTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_EMPLOYEE_CLASS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_EMPLOYER_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_EMPLOYMENT_CLASS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_EMPLOYMENT_STATUS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ENROLLMENT_REQUEST_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ENTITY_ID_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ENTITY_RELATIONSHIP_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ENTITY_SUB_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ENTITY_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ENTITY_TYPE_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_EPSDT_REFERRAL_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ERROR_MESSAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ETHNICITY_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_EXCEPTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_EXCEPTION_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FACILITY_CODE_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FACILITY_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FACILITY_TYPE_CODE_BACK')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FACILITY_TYPE_UB_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FAMILY_RELATIONSHIP')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FAP_SEARCH_RADIO_OPTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FEATURE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FEATURE_GROUP')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FIELD_EDIT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FILE_CONTENT_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FILE_DETAIL_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FILE_USAGE_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FOLLOW_UP_ACTION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FORMULARY_RESTRICTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FORMULARY_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_FREQUENCY_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_GENDER_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_HCS_REVIEW_DECISION_RSN')
INSERT INTO #protected_table_names(table_name) VALUES ('L_HEALTH_RELATED_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_HIERARCHICAL_CHILD_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_HIERARCHICAL_LEVEL_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_HIERARCHICAL_STRUCT_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_HISTORY_LABEL')
INSERT INTO #protected_table_names(table_name) VALUES ('L_HOLD_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ID_CARD_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ID_CODE_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_IDENTIFIED_ETHNICITY_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_IDENTIFIED_RACE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_INCOME_FREQUENCY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_INDUSTRY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_INLAY_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_INSURANCE_LINE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_INSURANCE_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_INTERCHG_ACK_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_INTERCHG_NOTE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_INTERVENTION_ACTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_INVOICE_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_INVOICE_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ISSUE_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ISSUE_PRIORITY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ISSUE_RESOLUTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ISSUE_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LABEL_STYLE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LANGUAGE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LANGUAGE_EDITOR_FILE_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LETTER_GENERATION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LEVEL_OF_CARE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LEVEL_OF_FRAILTY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LEVEL_OF_HELP')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LEVEL_OF_SERVICE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LOB_COVERAGE_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LOCALE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LOCALE_PROCEDURE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LOCATION_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LOCATION_SERVICE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LOCATION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LOCATION_XREF')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LOCKOUT_REASON')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LOG_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_LOOKUP')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MAIL_FOLDER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MAIL_RECIPIENT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MAIL_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MAIL_USER_REF')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MAINTENANCE_REASON_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MAINTENANCE_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MARITAL_STATUS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MARKET_COVERAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MEDICAL_SUBJECT_HEADING')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MEDICARE_ELIG_RSN_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MEDICARE_PLAN_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MEMBER_CONTACT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MEMBER_ID_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MEMBER_INFORMATION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MEMBER_INTERVENTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MEMBER_INTERVENTION_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MEMBER_INTERVENTION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MESSAGE_IN_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MESSAGE_IN_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MESSAGE_OUT_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MESSAGE_OUT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MOBILE_CARRIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_MONTH')
INSERT INTO #protected_table_names(table_name) VALUES ('L_NATURE_OF_CONDITION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_NDC_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_NEW_OR_EXISTING')
INSERT INTO #protected_table_names(table_name) VALUES ('L_NEWS_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_NOTE_REFERENCE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_NOTIFICATION_RECIPIENT')
INSERT INTO #protected_table_names(table_name) VALUES ('L_NUM_OF_FALLS_IN_YEAR')
INSERT INTO #protected_table_names(table_name) VALUES ('L_NURS_HOME_RES_STATUS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_O2_DELIVERY_SYSTEM_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_O2_EQUIPMENT_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_O2_TEST_CONDITION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_O2_TEST_FINDINGS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_OCCURRENCE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_OCCURRENCE_SPAN')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ONGOING_TREATMENT_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_OPEN_ENROLL_DATE_RULE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ORAL_CAVITY_DESIGNATION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ORGANIZATION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_ORIGINAL_CLAIM_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PAR_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PARTICIPANT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PASSWORD_QUESTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PATIENT_LOCATION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PATIENT_SIGNATURE_SOURCE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PATIENT_STATUS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PAY_TO_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PAYER_RESP_SEQ_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PAYMENT_ACTION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PAYMENT_FORMAT_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PAYMENT_METHOD_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PAYMENT_TRANSACTION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PCP_ASSIGNMENT_LEVEL')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PCP_OPTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_POLICY_COMPLIANCE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_POLICY_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_POST_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PREFERENCE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PREVENTATIVE_CARE_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PRICING_METHODOLOGY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROCEDURE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROCEDURE_MODIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROGNOSIS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROPERTY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROV_ACCEPT_ASSIGNMENT')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROV_ACCEPTING_PATIENT')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROV_AFFILIATION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROV_PAYMENT_STATUS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROV_PAYMENT_TRANS_ACTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROV_REG_ENTRY_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROVIDER_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROVIDER_LICENSE_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROVIDER_TAXONOMY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_PROVIDER_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_QUANTITY_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RA_DAY_COUNT_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RA_WORKFLOW_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RACE_ETHNICITY_COLLECTION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RAR_CLAIM_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REACTION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REASON_MED_PRIOR_AUTH')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RECOUP_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RECUR_DAY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RECUR_OCCURRENCE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RECUR_PATTERN')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REFERENCE_ID_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REGION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REIMBURSE_CONTRACT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REJECT_REASON_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RELATED_CAUSES_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RELATIONSHIP_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RELEASE_OF_INFO_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REMARK_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REMITTANCE_REMARK_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RENDER_STYLE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RENDER_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REPORT_TRANSMISSION_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REPORT_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REQUEST_ACTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REQUEST_CATEGORY_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REQUEST_QUEUE_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REQUEST_REASON')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REQUEST_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REQUEST_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REQUEST_VALIDATION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RESTRICT_SUB_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RESULT_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_REVENUE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RULE_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_RULE_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SCHEDULE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SCORECARD_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SCORECARD_SCORE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SERVICE_AUTH_EXCEPTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SERVICE_CATEGORY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SERVICE_CLASS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SERVICE_ID_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SERVICE_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SHIP_OR_CALENDAR_PATTERN')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SHIP_PATTERN_TIME_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SIC_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SNAPSHOT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SPECIAL_PROGRAM')
INSERT INTO #protected_table_names(table_name) VALUES ('L_STATE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_STAYWELL_COLLECTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_STAYWELL_CONTENT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_STUDENT_STATUS_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SUBJECT_AREA')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SUBLUXATION_LEVEL_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SUBSYSTEM_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SURVEY_REQUEST_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_SYSTEM_VERSION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TIER_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TIME_FRAME')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TIME_PERIOD_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TIME_ZONE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TOOTH_NUMBER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TOOTH_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TOOTH_SURFACE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TRACE_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TRANSACTION_HANDLING_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TRANSACTION_SET_ID_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TRANSACTION_SET_PURP_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TRANSACTION_TYPE_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TRANSACTION_USAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TREATMENT_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TREATMENT_PROGRAM_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TX_IN_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TX_OUT_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TX_OUT_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TX_REPORT')
INSERT INTO #protected_table_names(table_name) VALUES ('L_TYPE_OF_SERVICE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_UB04_CODE_LIST_QUALIFIER')
INSERT INTO #protected_table_names(table_name) VALUES ('L_UNIT_OF_MEASUREMENT_CODE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_USE_OF_LANGUAGE_IND')
INSERT INTO #protected_table_names(table_name) VALUES ('L_USER_ACTION')
INSERT INTO #protected_table_names(table_name) VALUES ('L_USER_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_VACCINE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_VERBOSE_LEVEL')
INSERT INTO #protected_table_names(table_name) VALUES ('L_VERIFICATION_STATUS')
INSERT INTO #protected_table_names(table_name) VALUES ('L_VIRTUAL_PARTICIPANT')
INSERT INTO #protected_table_names(table_name) VALUES ('L_WAITING_PERIOD_RULE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_WEEKDAY')
INSERT INTO #protected_table_names(table_name) VALUES ('L_WORKFLOW_ACTION_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_WORKFLOW_USAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('L_YES_NO_RESPONSE')
INSERT INTO #protected_table_names(table_name) VALUES ('LINK_PARAM')
INSERT INTO #protected_table_names(table_name) VALUES ('MENU')
INSERT INTO #protected_table_names(table_name) VALUES ('MENU_CONFIG')
INSERT INTO #protected_table_names(table_name) VALUES ('MENU_ITEM')
INSERT INTO #protected_table_names(table_name) VALUES ('MENU_LINK')
INSERT INTO #protected_table_names(table_name) VALUES ('MESSAGE_IN')
INSERT INTO #protected_table_names(table_name) VALUES ('MESSAGE_OUT')
INSERT INTO #protected_table_names(table_name) VALUES ('META_DATA_MAPPING')
INSERT INTO #protected_table_names(table_name) VALUES ('META_DATA_SOURCE')
INSERT INTO #protected_table_names(table_name) VALUES ('META_FK_PK')
INSERT INTO #protected_table_names(table_name) VALUES ('META_LOAD_ERRORS')
INSERT INTO #protected_table_names(table_name) VALUES ('META_LOAD_ORDER')
INSERT INTO #protected_table_names(table_name) VALUES ('META_LOAD_PROCS')
INSERT INTO #protected_table_names(table_name) VALUES ('PAGE')
INSERT INTO #protected_table_names(table_name) VALUES ('PERSONALIZED_CONTENT')
INSERT INTO #protected_table_names(table_name) VALUES ('PERSONALIZED_TOKEN')
INSERT INTO #protected_table_names(table_name) VALUES ('PREFERENCE_ENTITY_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('PREFERENCE_OVERRIDE')
INSERT INTO #protected_table_names(table_name) VALUES ('QUESTION')
INSERT INTO #protected_table_names(table_name) VALUES ('QUESTION_ANSWER')
INSERT INTO #protected_table_names(table_name) VALUES ('QUESTION_CHOICE')
INSERT INTO #protected_table_names(table_name) VALUES ('QUESTION_RESULTS')
INSERT INTO #protected_table_names(table_name) VALUES ('QUESTION_XREF')
INSERT INTO #protected_table_names(table_name) VALUES ('ROLE')
INSERT INTO #protected_table_names(table_name) VALUES ('ROLE_DEFAULT_WORKGROUP')
INSERT INTO #protected_table_names(table_name) VALUES ('ROLE_ENTITY_SUB_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('ROLE_RESTRICT_SUB_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('RULE_TYPE')
INSERT INTO #protected_table_names(table_name) VALUES ('RULE_TYPE_NOTIFY')
INSERT INTO #protected_table_names(table_name) VALUES ('RULES')
INSERT INTO #protected_table_names(table_name) VALUES ('RULESET')
INSERT INTO #protected_table_names(table_name) VALUES ('RULESET_REQUEST')
INSERT INTO #protected_table_names(table_name) VALUES ('STEP')
INSERT INTO #protected_table_names(table_name) VALUES ('STEP_ACTION')
INSERT INTO #protected_table_names(table_name) VALUES ('STEP_ACTION_RECIPIENT')
INSERT INTO #protected_table_names(table_name) VALUES ('STEP_PARTICIPANT')
INSERT INTO #protected_table_names(table_name) VALUES ('SUB_MENU_ITEM')
INSERT INTO #protected_table_names(table_name) VALUES ('SUCCESS_SCREEN')
INSERT INTO #protected_table_names(table_name) VALUES ('TABLE_KEY')
INSERT INTO #protected_table_names(table_name) VALUES ('TRANSITION')
INSERT INTO #protected_table_names(table_name) VALUES ('TRANSMISSION_IN')
INSERT INTO #protected_table_names(table_name) VALUES ('TRANSMISSION_OUT')
INSERT INTO #protected_table_names(table_name) VALUES ('TX_IN')
INSERT INTO #protected_table_names(table_name) VALUES ('TX_IN_ARCHIVE')
INSERT INTO #protected_table_names(table_name) VALUES ('TX_OUT')
INSERT INTO #protected_table_names(table_name) VALUES ('TX_RESULTS')
INSERT INTO #protected_table_names(table_name) VALUES ('TX_SET')
INSERT INTO #protected_table_names(table_name) VALUES ('TX_TABLE')
INSERT INTO #protected_table_names(table_name) VALUES ('USER_MENU')
INSERT INTO #protected_table_names(table_name) VALUES ('USER_MENU_CONFIG')
INSERT INTO #protected_table_names(table_name) VALUES ('USER_MENU_ITEM')
INSERT INTO #protected_table_names(table_name) VALUES ('USER_PREFERENCE')
INSERT INTO #protected_table_names(table_name) VALUES ('USER_PREFERENCE_HIST')
INSERT INTO #protected_table_names(table_name) VALUES ('USER_PREFERENCE_OVERRIDE')
INSERT INTO #protected_table_names(table_name) VALUES ('WORKFLOW')
INSERT INTO #protected_table_names(table_name) VALUES ('WORKFLOW_FORM')
INSERT INTO #protected_table_names(table_name) VALUES ('WORKFLOW_PARTICIPANT')
INSERT INTO #protected_table_names(table_name) VALUES ('WORKFLOW_REQUEST')
INSERT INTO #protected_table_names(table_name) VALUES ('WORKGROUP')
INSERT INTO #protected_table_names(table_name) VALUES ('WORKGROUP_PARTICIPANT')

-- Remove any protected tables from the list
DELETE T
  FROM #table_names				T
  JOIN #protected_table_names	P
    ON T.table_name				= P.table_name

--*************************************************************************************************
-- Create the log
--*************************************************************************************************
INSERT INTO dbo.DRLog
      (cutoff_date
	  ,start_time
	  ,email_address)
SELECT @cutoff_date
      ,GETDATE()
	  ,'dkunkle@evolenthealth.com'

SELECT @log_id = SCOPE_IDENTITY()

--*************************************************************************************************
-- Loop through the tables calling the stored procedure to do the delete
--*************************************************************************************************
DECLARE Table_Cursor CURSOR FOR
 SELECT table_name
   FROM #table_names
  ORDER BY table_name

   OPEN Table_Cursor
  FETCH NEXT FROM Table_Cursor
   INTO @table_name

WHILE @@FETCH_STATUS = 0
	BEGIN	
	
		EXEC spPortal_DeleteTableData @log_id, @cutoff_date, @table_name
		FETCH NEXT FROM Table_Cursor
	     INTO @table_name
	END

CLOSE Table_Cursor
DEALLOCATE Table_Cursor

--*************************************************************************************************
-- Complete the log
--*************************************************************************************************
UPDATE dbo.DRLog
   SET end_time		= GETDATE()
 WHERE log_id		= @log_id

--*************************************************************************************************
-- Cleanup
--*************************************************************************************************
IF OBJECT_ID('tempdb.dbo.#table_names') IS NOT NULL
	BEGIN DROP TABLE #table_names END

END